version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
    - 5432:5432
    volumes:
	- ./sql:/docker-entrypoint-initdb.d

    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB


  adminer:
    image: adminer
    restart: always
    ports:
     - 8080:8080
